#!/bin/bash
kokaDir=$KOKADIR
sourceDir="$(pwd)"
outputDir="$sourceDir/out"
kokaExec="$kokaDir/out/release/koka-0.9.0-dev"
kokaLibDir="$kokaDir/lib"
kokaTestDir="$kokaDir/test"
kokaFlags=-"i$sourceDir -i$kokaLibDir -i$kokaTestDir --core -o$outputDir"

pushd $kokaDir
$kokaExec $kokaFlags -c $1
popd 
